### ISSUE TITLE
Could not find module 'Valet' for target 'x86_64-apple-ios-simulator'

### ISSUE THREAD

**Issue by qsd-faris** [square/Valet#306] opened 2023-11-28 13:53 UTC
I have 3 schemes in my app. I am not sure why but when running **on iOS simulator** on one of these schemes(Debug), I get the following error on the `import Valet` line:
`Could not find module 'Valet' for target 'x86_64-apple-ios-simulator'; found: arm64-apple-ios-simulator, at: /Users/me/Library/Developer/Xcode/DerivedData/project-bgumdcxgpxtntlgtykppxpaxjcji/Index.noindex/Build/Products/Debug-iphonesimulator/Valet.swiftmodule`

<img width="753" alt="Screenshot 2023-11-28 at 14 51 51" src="https://github.com/square/Valet/assets/92013327/0312b31a-7849-48a8-b839-2de3839152cf">

Running on any other scheme will succeed, and also **running this scheme will work on real device**, but the problem seems to be when running in iOS simulator. Does anyone know why? I have tried to make `Build Settings` be the same for all schemes, but no success.

**Library was installed using SPM**. Before that, it was working fine using Cocoapods. I did not change anything except removing the pod and removing its framework from `Other Linker Flags`(because Xcode was complaining about that).

This was not the case with another library I switched from Cocoapods to SPM, everything worked fine.

**Comment by dfed** [comment] 2023-11-28 14:42
Can you reproduce this issue in a sample project you can share? Hard for me to intuit what could be wrong here.

This is unlikely to be an issue with Valet's Package configuration is not scheme-specific. I'm happy to help if I can but again, I'd need a sample project if my help is going to comprise more than wild guesses and directional advice.

To clarify a couple things:
1. Does Valet build to simulator in any other scheme for you?
2. Does Valet build to device in all schemes for you?

Given that you had to delete things from other linker flags after removing the Cocoapod integration, my wild guess is that your project is misconfigured: you likely accidentally brought CP-generated build flags into your Debug scheme, and you haven't found&fixed them all yet. (I have had the Other Linker Flags issue before. It's pretty easy to accidentally bring CP-generated stuff into your scheme)

If I were you: I'd delete + recreate my Debug scheme and see if that fixes it. If it does, run a diff on what changed and one of those changes was the problem.

**Comment by qsd-faris** [comment] 2023-11-28 14:49
@dfed thanks for the quick answer. I have tried with sample project and everything was working fine.
Answer to both of your questions is - Yes, it builds.
I have also tried making my Debug scheme looks the same as other scheme but no success building it on simulator again.
It is weird how it looks for another library. There definitely must be something.

**Comment by dfed** [comment] 2023-11-28 15:27
There's nothing about Valet that requires Rosetta. So there's something that's forcing you into this mode that is causing the issue 🤔

**Comment by qsd-faris** [comment] 2023-11-28 23:01
@dfed yeah, it is definitely something up to scheme. However, for future reference, I am posting the popup that Xcode15 shows when running the scheme on the iOS simulator. Maybe someone else already faced this and will be able to help me:

<img width="420" alt="Screenshot 2023-11-28 at 23 59 09" src="https://github.com/square/Valet/assets/92013327/6a078322-92fd-46e4-838a-023860f2595b">

**Comment by dfed** [comment] 2023-11-29 15:56
@qsd-faris I asked around and got this particular bit of insight that may help you: you likely have an exclusion of `arm64` somewhere in your build settings. This could be in either your xcodeproj or your Podfile. Running `git grep arm64` on your repo will likely help you find out where this is.

You may also be able to confirm this theory by filtering your build log for `x86_64` – if you see that while on an ARM Mac, you almost certainly are preventing building for `arm64` and that is causing your issue with SPM.

**Comment by qsd-faris** [comment] 2023-11-30 14:55
@dfed thank you very much. I was also afraid that arm64 was the issue because I needed to put it in Excluded architectures because Xcode is showing errors for pods like: `No such module podName` without that... 

What is weird here is that I have `arm64` in excluded arch for each scheme and only one scheme is not running...

**Comment by dfed** [comment] 2023-12-14 18:19
Closing this one out since we aren't getting much traction and I do not believe this is a Valet issue. Might be a better q for iOS dev support slacks.

**Closed** 2023-12-14 18:19 UTC

**Comment by sapnabansaltrinet** [comment] 2024-09-27 11:00
Hi, I am also facing the same issue regarding the Valet framework 
"ERROR: [ContentDelivery.Uploader] Asset validation failed (90087) Unsupported Architectures. The executable for XYZ.app/Frameworks/Valet.framework contains unsupported architectures '[i386, x86_64]'. (ID: cb75bc79-16f8-4eaf-ab64-b0c9e20e3f7f)"

In my project under the excluded arm64 is added and in pod file x86_64 added for other library.
Valet framework  added using embedded and linked with binary framework in the build face option not using pods for that.

Please help me on that.
