### ISSUE TITLE
TouchID popup not showing in some cases after retrieving an entry with `.userPresence`

### ISSUE THREAD

**Issue by tijme** [square/Valet#187] opened 2019-09-27 20:22 UTC
Since iOS 13 the TouchID prompt is not working correctly anymore. The first time retrieving items with `.userPresence` the TouchID popup shows, but after calling it for a second time, it stops working and the TouchID popup will not show.

This is exactly as this problem describes: https://forums.developer.apple.com/thread/121149. Whenever you shake the iDevice, the TouchID popup will appear.

My app has this issue when unlocking it via TouchID. It's open-source and might come in handy if you want to reproduce the behaviour: https://github.com/tijme/raivo/tree/317115bae9dcd0c2e56878fff284183cc3444ff5.

I'm not sure if this is an issue within Valet or if this is a bug, but I just wanted to let you know that this issue occurs when using the Valet package.

**Comment by dfed** [comment] 2019-09-30 12:57
I just tested this using a modified version of the `ValetTouchIDTest` target (modified to use `SecureEnclaveValet` rather than `SinglePromptSecureEnclaveValet`), and the biometric prompt occurred on every access. Note that I'm testing on a phone with Face ID running iOS 13.1., rather than a phone with Touch ID (that shouldn't make a difference, however). What build of iOS 13 are you running?

I'm guessing [this](https://github.com/tijme/raivo/blob/317115bae9dcd0c2e56878fff284183cc3444ff5/Raivo/Helpers/StorageHelper.swift#L278) is the code that is misbehaving?

When the TouchID popup fails to appear, do you still get access to the underlying data, or no? Since I'm unable to reproduce, more information would be helpful. Are there any console log messages that seem related? This sounds like an OS-level bug – without more information it's going to be difficult for me to figure out if there's a workaround.

**Comment by tijme** [comment] 2019-09-30 18:16
Hi @dfed,

I'm running iOS 13.1.1 (stable) on my iPhone 7. You are right about the part of the code that is misbehaving. 

I just debugged it and found out that the code pauses on [this](https://github.com/square/Valet/blob/0d3fb186e1b235e8c99bead4af5146afb9ca3ca1/Sources/Valet/Internal/SecItem.swift#L123) line in Valet.

I guess this is normal behaviour, as `SecItemCopyMatching` will wait until the user authenticates itself via TouchID. This means calling this functions should show the TouchID popup (correct me if I'm wrong). However, when reaching the `SecItemCopyMatching` the TouchID popup does not show on my iPhone, as described in the [forum post](https://forums.developer.apple.com/thread/121149) that I linked earlier.

At this point, the following log line is visible in my Xcode output:

```2019-09-30 20:02:17.836219+0200 Raivo[1505:239833] Can't find keyplane that supports type 4 for keyboard iPhone-PortraitChoco-NumberPad; using 25671_PortraitChoco_iPhone-Simple-Pad_Default```

However, I guess this log line is irrelevant to the issue. This means I don't have any more information unfortunately. You might be right on your thought that this might be an OS-level bug.

The weird thing is that, as described in the forum post, the TouchID popup appears when you shake your iPhone. At that point you can either cancel TouchID authentication by tapping "Cancel" on the popup, or you can authenticate by placing your finger on the home button. Either one of these actions will continue the runtime and `SecItemCopyMatching` will finish running.

**Comment by dfed** [comment] 2019-09-30 19:03
> I just debugged it and found out that the code pauses on [this](https://github.com/square/Valet/blob/0d3fb186e1b235e8c99bead4af5146afb9ca3ca1/Sources/Valet/Internal/SecItem.swift#L123) line in Valet.

That's great info! That means that we're hanging on the OS call. With that information I can say with confidence that this is an OS-level bug: the OS is failing to present the prompt, so it's failing to give us an answer, so we're hanging forever.

If I had to guess, most iOS developers at Apple are testing on iPhones that use Face ID rather than Touch ID, and therefore this bug slipped through. This is a pretty terrible bug for users with Touch ID phones. *Please* use [Feedback Assistant](https://feedbackassistant.apple.com) to file a bug with Apple.

As this is an OS-level bug, I'm going to close this issue. While this issue is awful, I don't see a way that I could offer an in-library workaround. If you get more info, feel free to post it here: it'll be helpful to the next person who hits this issue.

**Closed by dfed** 2019-09-30 19:03 UTC

**Comment by tijme** [comment] 2019-10-01 07:33
Thanks @dfed, I've just filed a bug at Apple using the Feedback Assistant.

**Comment by tijme** [comment] 2019-10-27 14:47
Just for reference, 9to5mac [wrote about this bug](https://9to5mac.com/2019/09/30/ios-13-iphone-touch-id-login-bug/). It's indeed an OS-level bug. According to [multiple users](https://forums.developer.apple.com/thread/121149) on the Apple Developer forum the bug has been fixed in iOS 13.2 beta 2.

**Comment by dfed** [comment] 2019-10-27 14:57
Appreciate your closing the loop. Excited to have this fixed soon!
