### ISSUE TITLE
No Touch ID prompt when retrieving stored use Touch ID access control

### ISSUE THREAD

**Issue by dtrenz** [square/Valet#111] opened 2017-05-26 16:39 UTC
I am storing & retrieving data using a `VALSecureEnclaveValet` with a Touch ID access control policy. But when I read the data out of the keychain via Valet, the user is not prompted for their fingerprint but the data is read, anyway.

Here is my implementation:

```swift
let valet = VALSecureEnclaveValet(identifier: Constants.valetIdentifier, accessControl: .touchIDAnyFingerprint)

let secretStringKey = "secret"

secureEnclaveValet.setString(secretString, forKey: "secret") 

// Expected: Touch ID prompt should be presented to user in order to read secret string
// Actual: No prompt appears, string is still read w/o any fingerprint verification
let secretString = secureEnclaveValet.string(
    forKey: "secret",  
    userPrompt: "Fingerprint required to read secret", 
    userCancelled: nil)
```

Am I implementing this incorrectly, or misunderstanding how this is supposed to work?

Any help is appreciated. Thank you.

**Comment by dfed** [comment] 2017-05-30 03:26
Thanks for the report! I tried, but I am unable to reproduce the issue you describe on a device: every time I call `string(forKey:userPromt:userCancelled:)` I am prompted for Touch ID.

I'm curious if you can reproduce this issue using the included test application `ValetTouchIDTest`. I tried making the following modifications to simulate your parameters above but I was still prompted for Touch ID as expected:
```
diff --git a/ValetTouchIDTest/ValetTouchIDTestViewController.swift b/ValetTouchIDTest/ValetTouchIDTestViewController.swift
index e63bf4d..540bb15 100644
--- a/ValetTouchIDTest/ValetTouchIDTestViewController.swift
+++ b/ValetTouchIDTest/ValetTouchIDTestViewController.swift
@@ -26,7 +26,7 @@ final class ValetTouchIDTestViewController : UIViewController
     // MARK: Properties
 
     @IBOutlet var textView : UITextView?
-    var singlePromptSecureEnclaveValet : VALSinglePromptSecureEnclaveValet
+    var singlePromptSecureEnclaveValet : VALSecureEnclaveValet
     let username = "CustomerPresentProof"
 
 
@@ -34,7 +34,7 @@ final class ValetTouchIDTestViewController : UIViewController
 
     required init?(coder aDecoder: NSCoder)
     {
-        if let valet = VALSinglePromptSecureEnclaveValet(identifier: "UserPresence", accessControl: VALAccessControl.userPresence) {
+        if let valet = VALSecureEnclaveValet(identifier: "UserPresence", accessControl: VALAccessControl.touchIDAnyFingerprint) {
             self.singlePromptSecureEnclaveValet = valet
         } else {
             return nil;
@@ -58,7 +58,7 @@ final class ValetTouchIDTestViewController : UIViewController
     @IBAction func getItem(sender: UIResponder)
     {
         var userCancelled: ObjCBool = false
-        let password = singlePromptSecureEnclaveValet.string(forKey: username, userPrompt: "Use TouchID to retrieve password", userCancelled:&userCancelled)
+        let password = singlePromptSecureEnclaveValet.string(forKey: username, userPrompt: "Use TouchID to retrieve password", userCancelled:nil)
 
         var resultString: String
         if (userCancelled.boolValue) {
@@ -89,7 +89,7 @@ final class ValetTouchIDTestViewController : UIViewController
     @objc(requirePrompt:)
     @IBAction func requirePrompt(sender: UIResponder)
     {
-        singlePromptSecureEnclaveValet.requirePromptOnNextAccess()
+//        singlePromptSecureEnclaveValet.requirePromptOnNextAccess()
         updateTextView(messageComponents: #function)
     }
```

If you are able to reproduce the issue using the test application (or any other test application you can share), please share the diff/code with us. Also, please let us know exactly what device & operating system version you're running the code on, as well as what Xcode version you're running. Thanks!

**Comment by dtrenz** [comment] 2017-05-30 14:16
Thanks for the suggestion, @dfed.

I just ran the test app on a simulator and never saw the prompt.

```
Simulator: iPhone 7 (10.3)
Xcode: 8.3.2
```

<img width="487" alt="screen shot 2017-05-30 at 10 14 55 am" src="https://cloud.githubusercontent.com/assets/639833/26587650/e59f03a6-4520-11e7-94c8-091b612e52d2.png">

**Comment by dfed** [comment] 2017-05-30 15:46
The simulator doesn't have Touch ID, so there is no prompt. If you ask a device without Touch ID to prompt for Touch ID, it'll just give you the values. Keep in mind that the sim doesn't have a passcode either, so even using `.userPresence` won't prompt for a passcode.

In short: test your Secure Enclave keychain code on device if you want to see real authentication challenges. Since Valet is working as expected, I'm closing this issue out.

**Closed by dfed** 2017-05-30 15:46 UTC

**Comment by dtrenz** [comment] 2017-05-30 16:59
> The simulator doesn't have Touch ID, so there is no prompt. 

This is not accurate. The iOS simulator can indeed simulate Touch ID. It can display the prompt, and even simulate a successful or unsuccessful fingerprint match:

![image](https://cloud.githubusercontent.com/assets/639833/26594824/36a4498a-4537-11e7-9a6f-85480523979d.png)

Since this wasn't working with Valet, I implemented Local Authentication via Touch ID myself and I see a Touch ID prompt in the simulator, and it works.

Here is a snippet of the code I am using to display the fingerprint prompt:
```swift
LAContext().evaluatePolicy(.deviceOwnerAuthenticationWithBiometrics, localizedReason: "Provide your fingerprint") { (wasFingerprintVerified, error) in
    if let error = error {
        print(error.localizedDescription)
    }
            
    guard wasFingerprintVerified else { 
        print("Fingerprint did not match.")
        return
    }

    print("Fingerprint was successfully matched!")
}
```

**Comment by dfed** [comment] 2017-05-30 17:01
Keychain and LocalAuthentication libraries work differently. Test authenticated keychain calls on device.

**Comment by dtrenz** [comment] 2017-05-30 17:35
Ah, OK. I see now. Sounds like a bug for Apple, then. I am seeing the Touch ID prompt when running on a device. I wonder why it doesn't prompt on a simulator, even though the iOS simulator clearly can prompt for Touch ID?

Anyway, thanks for clearing this up!

**Comment by dfed** [comment] 2017-05-30 17:47
For the sake of my unit tests, I'm kinda happy that the prompts don't work in the sim 😉. But a consistent usage of the authentication API would be a nice improvement over the current bifurcated state, for sure.

As an aside, it's good to remember that Keychain's API was written in C, and is quite low-level. The API effectively hasn't undergone an overhaul since its original release... LocalAuthentication was built next to Keychain (neither API talks to the other). If you're curious, the `SecItem` underlying implementation is [open source](https://opensource.apple.com/source/Security/Security-55471/libsecurity_keychain/lib/SecItem.cpp.auto.html) – having the source was instrumental in figuring out some of the undocumented differences in iOS's keychain implementation and macOS's keychain implementation.
