### ISSUE TITLE
Facing issue while uploading app on App Store : "ERROR: [ContentDelivery.Uploader] Asset validation failed (90087) Unsupported Architectures. The executable for XYZ.app/Frameworks/Valet.framework contains unsupported architectures '[i386, x86_64]'. (ID: cb75bc79-16f8-4eaf-ab64-b0c9e20e3f7f)"

### ISSUE THREAD

**Issue by sapnabansaltrinet** [square/Valet#321] opened 2024-09-27 13:05 UTC
Hi, I am also facing the same issue regarding the Valet framework using static library not with pod installation while submit app on App Store. On my local machine it's working fine.
Valet framework added using embedded and linked with binary framework in the build face option not using pods for that.

"ERROR: [ContentDelivery.Uploader] Asset validation failed (90087) Unsupported Architectures. The executable for XYZ.app/Frameworks/Valet.framework contains unsupported architectures '[i386, x86_64]'. (ID: cb75bc79-16f8-4eaf-ab64-b0c9e20e3f7f)"

In my project under the excluded arm64 is added and in pod file x86_64 added for other library.

One more thing if I tried to sue the Valet pod its giving error on this line :
@interface VALValet () "Cannot find interface declaration for 'VALValet'"

Tofix this I have imported the framework like that #import <Valet/VALValet .h> previously its added in that format
"#import <Valet/Valet.h>" for static library in am thinking. After importing the header its crashing and giving different error:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[VALValet initWithSharedAccessGroupIdentifier:accessibility:]: unrecognized selector sent to instance 0x60000048d600'

Please a anyone guide me how to fix this issue on urgent bases because I have to submit app as per as soon.

**Comment by dfed** [comment] 2024-09-27 15:03
What version of Xcode are you using? What version of Valet? Have you ever seen this work? If so: did you change something recently?

A sample project that reproduces the issue would help.

**Comment by sapnabansaltrinet** [comment] 2024-09-28 21:36
I am using Xcode 16 and pod version of valet  is 4.3.0. ITs working fine with linked with binary files and embed one but failed to upload on appstore.. But when I tried to use by pods its crashing on this line :
 id<OAuthSecureStorage> secureStorage = [[VALValet alloc] initWithSharedAccessGroupIdentifier:@"com.abcOAuth"
                                                                                   accessibility:VALAccessibilityAlways];

I have imported the header in the objective c file "#import <Valet/VALValet.h>"

Please let me how this will work or share any sample project in objective c with setting all the configuration setting and the above method usage.

**Comment by sapnabansaltrinet** [comment] 2024-09-30 12:18
If I remove the arch x86_64 and i386 frommthe4 executable file giving this error : 

ld: warning: ignoring file '/Users/sbansal/Documents/Zenefit_IOS_APP/Valet.framework/Valet': fat file missing arch 'x86_64', file has 'armv7,arm64'
ld: warning: Could not find or use auto-linked framework 'CoreAudioTypes': framework 'CoreAudioTypes' not found
ld: warning: Could not parse or use implicit file '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/SwiftUICore.framework/SwiftUICore.tbd': cannot link directly with 'SwiftUICore' because product being built is not an allowed client of it

**Comment by dfed** [comment] 2024-09-30 13:58
Apologies for the slow response: I missed your earlier message.

> But when I tried with pods its crashing on this line :
> id secureStorage = [[VALValet alloc] initWithSharedAccessGroupIdentifier:@"com.abcOAuth"
accessibility:VALAccessibilityAlways];

Uhh, what is the crash? Valet doesn't have any asserts here, nor is it doing anything dangerous in the initializer.

You mentioned a couple other dependencies (saying "etc" is not helpful!), but I'd be curious how you're integrating those other dependencies, and if any of them are prebuilt binaries. I'd guess that you have a dependency with a pre-built binary and haven't integrated it correctly. I'd also guess that you're using multiple dependency manager systems that might not work well together.

This really does not seem like an issue with Valet, but rather something incorrect with your app's build configuration. To be blunt: without a sample project that reproduces the build issue I am afraid that I nor anyone else is going to be much help. There's just too many things that could be going wrong here: I have shipped nearly a half dozen apps that depend on Valet utilizing multiple dependency managers and I have not encountered the issues you are describing.

I strongly suggest making a minimally reproducing sample project. Doing so will help you isolate what is wrong, and may help others help you. That said, I have a pretty busy week coming up and personally I am unlikely to be of much direct assistance within the time frame you need.

I'm going to close this issue, because given the above I am convinced that the issue is not in Valet. However, I'm still subscribed here in case you can upload a sample project / provide more clarity and I have time to help a stranger with an issue that is at best tangentially related to this repo.

**Closed** 2024-09-30 13:59 UTC

**Comment by dfed** [comment] 2024-09-30 14:34
Scrolling further up: I see that the exception you're experiencing is

> unrecognized selector sent to instance 0x60000048d600'

Again, this really seems like a build configuration problem and not a Valet problem. Kinda seems like the Valet library was not actually linked in this build configuration.
