### ISSUE TITLE
Xcode 12 - Valet Framework not compiling on Dynamic Library Mach-O

### ISSUE THREAD

**Issue by harishios** [square/Valet#250] opened 2020-11-05 03:20 UTC
Hi Team,

Valet Framework is not compiling in my project when the Mach-O is set to Dynamic Lib on Xcode 12, I need to make that Static in order to compile it for me.

Please help here. PFA of screenshot for reference 
<img width="897" alt="Screen Shot 2020-11-04 at 5 46 25 PM" src="https://user-images.githubusercontent.com/18008999/98193761-c874df00-1ed2-11eb-8759-827a70248af6.png">

**Comment by dfed** [comment] 2020-11-05 04:38
Thank you for filing @harishios, but there isn't yet enough information for me to help. Some starter questions:

1. Do other projects compile for you using these settings? If so, which ones? If you haven't tried any other projects, can you try another Swift-only one?
2. Can you reproduce this error in a sample project? If so, can you attach that sample project to this issue?
3. How are you integrating Valet (manually? with Cocoapods? Carthage? something else?)?

**Comment by harishios** [comment] 2020-11-05 04:55
1. I'm on Obj C project, Firebase can run with Dynamic Library on Xcode12
2. I haven't tried yet, but I can try one tomorrow
3. Cocopods

**Comment by harishios** [comment] 2020-11-05 15:31
Does making the `Valet Framework `to **Static Library** will be an issue?

**Comment by dfed** [comment] 2020-11-05 15:54
Statically linking Valet should work just fine.

**Comment by harishios** [comment] 2020-11-05 16:33
Thank you! We've to make to it static on `Podfile` to make the project run on Xcode 12,

`
$static_framework = ['Valet']

pre_install do |installer|
  installer.pod_targets.each do |pod|
    if $static_framework.include?(pod.name)
      def pod.build_as_static_framework?;
        true
      end
    end
  end
end`

**Comment by dfed** [comment] 2020-11-05 18:10
Can you post the podfile you were using prior to this change? I'd love to see if I can reproduce.

**Comment by harishios** [comment] 2020-11-05 18:11
platform :ios, '10.0'
use_frameworks!

target 'MyProject' do
    pod 'Valet'

end

**Comment by dfed** [comment] 2020-11-06 01:47
@harishios another q: what version of Cocoapods are you using?

**Comment by harishios** [comment] 2020-11-10 05:07
sorry for delayed response. 
**Pod version: 1.10.0**

**Comment by dfed** [comment] 2020-11-10 15:28
Thanks for letting me know @harishios!

Based on some googling, this looks like [a Cocoapods issue](https://github.com/CocoaPods/CocoaPods/issues/10063) and not something Valet can fix. I'm closing this out.

**Closed** 2020-11-10 15:28 UTC

**Comment by zhangjianshuai** [comment] 2021-02-22 05:12
just create a swift file in project which can solve this problem;
reference: 
https://stackoverflow.com/questions/52536380/why-linker-link-static-libraries-with-errors-ios/56176956#56176956
