### ISSUE TITLE
Build Error: Include of non-modular header inside framework module 'Valet.Valet'

### ISSUE THREAD

**Issue by mownier** [square/Valet#107] opened 2017-02-14 06:03 UTC
I got this error when I tried to build including the Valet framework, installed via Cocoapod.

<img width="236" alt="screen shot 2017-02-14 at 1 59 15 pm" src="https://cloud.githubusercontent.com/assets/3685613/22917159/0aca767a-f2be-11e6-8d97-f6cf66961315.png">

- Valet v2.3.0
- Cocoapod v1.2.0
- Xcode 8.0
- Swift3-Compatible Project

**Comment by dfed** [comment] 2017-02-14 15:30
Thanks for the report @mownier! Can you please screen shot the full expanded error and attach the build log with the error in it? Do you know if this also occurred in Cocoapods 1.1?

**Comment by mownier** [comment] 2017-02-15 08:46
@dfed Sorry, I can not screen shot the full expanded error. I think the errors on Valet's source files are having the same message:
```
Include of non-modular header inside framework module 'Valet.valet'
```

I don't know if that error occurred in Cocoapods 1.1.

When I used Carthage, same errors were still appearing. But when I tried to manually added all the necessary Valet's source files, the errors disappeared.

**Comment by dfed** [comment] 2017-02-15 15:42
I have three apps that consume Valet: one that uses Carthage, one that uses Cocoapods, and one via submodules. I'm not seeing an error in any of them, so I'm a bit lost.

I'm thrown by the error message's mention of `Valet.valet`: that message reads like we're trying to import `Valet.h` somewhere. But the only places we do that are in unit tests and in the TouchIDTest app, which aren't included in the frameworks.

Do you know what file the issue is occurring in? When you say you "tried to manually added all the necessary Valet's source files, the errors disappeared", what did you change? Can you attach your diff to the Valet project? And of course, a sample project would be immensely helpful.

**Comment by mownier** [comment] 2017-02-16 09:45
Here is a related issue: https://github.com/aws/aws-sdk-ios/issues/413

Full description of the build error related to Valet:
<img width="527" alt="screen shot 2017-02-16 at 5 42 23 pm" src="https://cloud.githubusercontent.com/assets/3685613/23015861/6c101036-f46f-11e6-983b-696270a1bf55.png">

**Comment by dfed** [comment] 2017-02-16 14:59
Can you fold down one of the triangles in the screenshot? Seeing what file and line in Valet is causing the problem would be seriously helpful.

Again, when you say you "tried to manually added all the necessary Valet's source files, the errors disappeared", what did you change? Can you attach your diff to the Valet project?

You have a lot more information than you're giving me. Given that I can't reproduce, please give me all the information you can.

**Comment by mownier** [comment] 2017-02-17 08:14
<img width="980" alt="screen shot 2017-02-17 at 4 10 31 pm" src="https://cloud.githubusercontent.com/assets/3685613/23057558/ac384ea0-f52b-11e6-813b-99d29a1b23ed.png">

No, I don't modify the Valet project itself. What I just did was, I manually added all the Valet's source files in my project. No Cocoapods, Carthage, and gitmodule was used.

**Comment by dfed** [comment] 2017-02-17 16:27
Thanks for the additional info! Looks like Cocoapods is generating a bad umbrella header. @justinseanmartin any ideas?

**Comment by justinseanmartin** [comment] 2017-02-18 00:58
@dnkoutso - ideas on this?

**Comment by dnkoutso** [comment] 2017-02-18 00:59
@mownier do you `use_frameworks!` in your Podfile?

**Comment by mownier** [comment] 2017-02-18 02:30
yep, it is in the Podfile.

**Comment by justinseanmartin** [comment] 2017-02-19 22:05
How're you importing Valet in your source files? I just set up a new test app with Xcode 8.2.1, Cocoapods 1.2.0, with Swift 3. 

In the Swift 3 sources, I imported Valet with `import Valet` and in the sources, I put a sample line in the AppDelegate.swift with `VALValet.init(identifier: "", accessibility: VALAccessibility.always)`. Everything builds just fine.

@mownier - Can you set up a sample project and upload it to GitHub showing the error you're hitting? It just needs to show how you're using it and how you're hitting the error.

**Comment by dfed** [comment] 2017-06-28 17:13
Closing this out. If this issue is still occurring please let us know (answering the above qs) and we'll re-open.

**Closed by dfed** 2017-06-28 17:13 UTC
