### ISSUE TITLE
Could not find shared access group prefix

### ISSUE THREAD

**Issue by ksm** [square/Valet#47] opened 2015-10-01 18:04 UTC
Started seeing the `Could not find shared access group prefix` error right after upgrading to OS X El Capitan. This is while running the app from Xcode 7.0.1 on a real device.

It happened one time when running the app itself. Removing and rerunning the app made it go away.

Happened a second time when running my app's share extension (which accesses the shared keychain group).

Happens when Valet is calling `_sharedAccessGroupPrefix` in `VALValet.m`. Valet asserts on:

    VALCheckCondition(status == errSecSuccess, nil, @"Could not find shared access group prefix.");

Any ideas?

**Comment by dfed** [comment] 2015-10-01 18:11
Seems sounds like a duplicate of #10 (see the [Debugging](https://github.com/square/Valet/blob/master/README.md#debugging) section of the README), and possibly related to #33. Keychain is notoriously unreliable when running on device through Xcode. I strongly recommend making signed builds to test keychain. Am I right to assume you haven't seen this issue in a signed build?

When you hit this issue in debug, just cancel the run and hit Run once more. It'll likely work the second time (thanks, Xcode).

Closing this out for now. Happy to re-open if you need more help or if you uncover more information (or possible incompatibility issues).

**Closed by dfed** 2015-10-01 18:11 UTC

**Comment by ksm** [comment] 2015-10-01 18:22
You're right, rerunning does make it go away. 

Are all debug builds unsigned then? I've got my certificate and provisioning profile explicitly setup for debug builds too. I'm following [Jared Sinclair's guide](http://blog.jaredsinclair.com/post/116436789850/follow-these-guidelines-and-never-struggle-with) for setting them up, so you could say I'm being pretty pedantic here.

**Comment by dfed** [comment] 2015-10-01 18:29
My understanding is debug builds are either unsigned or signed differently – not using a provisioning profile, for example – than non-debug builds. I'm not an expert on signing, however (cc @justinseanmartin  and @mtauraso who are). 

Running debug builds on device from Xcode is a recipe for signing sadness. Keychain issues in debug builds are usually red herrings (unless you can repro them in a properly signed build). I have a `NSAssert([loginValet canAccessKeychain])` at the beginning of `applicationDidFinishLaunching:`, which alerts me that Xcode screwed up quite quickly.

**Comment by justinseanmartin** [comment] 2015-10-01 21:07
All builds that are built for iOS devices need to be code signed, but they can be signed for development, enterprise distribution, or app store distribution. I believe you should be able to sign Debug builds with any of the above identities, but it is standard to sign Debug builds with your developer identity and sign Release builds with the app store identity. 

I wouldn't expect that it is code signing that is causing problems, but more likely an issue with how xcode installs developer apps or the black magic of how Xcode is picking a certificate/provisioning profile/code signing identity/teamID is messing something up.

@dfed - Would it make sense to move the NSAssert with a helpful error message for canAccessKeychain into Valet initialization for debug builds on real devices with a helpful failure message?

**Comment by dfed** [comment] 2015-10-01 21:17
I don't believe that consumable projects should assert if it can be avoided. That's why we wrote the [Debugging](https://github.com/square/Valet/blob/master/README.md#debugging) section in the README.

Moreover, different Valet configurations might be inaccessible under different configurations, so any `NSAssert` we put into the code might not be looking at a helpful configuration.

**Comment by ksm** [comment] 2015-10-02 19:24
@dfed @justinseanmartin Thank you for the in-depth explanation. Happy I'm not the only one on the flaky code signing while developing boat.

Happy to report the issue did not reappear since the start of this thread.

Will use the `NSAssert([loginValet canAccessKeychain])` assertion to aid in my development. Thanks for the protip.
